In [2]:
import numpy as np
import tensorflow as tf

In [3]:
#slicing 개념을 아는 것이 필요

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [4]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [5]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [7]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [8]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  76158.51 
Prediction:
 [[-108.83209 ]
 [-126.42334 ]
 [-127.144684]
 [-136.11615 ]
 [ -96.99266 ]
 [ -66.811676]
 [ -99.18953 ]
 [ -70.019455]
 [-113.970276]
 [ -99.591995]
 [ -96.668594]
 [ -92.30168 ]
 [-133.85114 ]
 [-114.27255 ]
 [ -98.68407 ]
 [-126.383316]
 [-110.326355]
 [-118.813675]
 [-128.65552 ]
 [-115.0331  ]
 [-116.75264 ]
 [-116.40645 ]
 [-112.352066]
 [-115.4538  ]
 [-132.965   ]]
100 Cost:  11.917013 
Prediction:
 [[150.73024 ]
 [185.37758 ]
 [180.16917 ]
 [198.5208  ]
 [140.80647 ]
 [108.40916 ]
 [151.26927 ]
 [115.620384]
 [177.32812 ]
 [170.09294 ]
 [144.63763 ]
 [145.5371  ]
 [183.696   ]
 [149.76382 ]
 [152.89507 ]
 [189.98816 ]
 [141.14323 ]
 [181.76828 ]
 [174.11441 ]
 [155.88284 ]
 [176.94402 ]
 [176.0655  ]
 [167.69348 ]
 [146.3628  ]
 [190.23126 ]]
200 Cost:  11.44354 
Prediction:
 [[150.8313  ]
 [185.33691 ]
 [180.21667 ]
 [198.5239  ]
 [140.77524 ]
 [108.29202 ]
 [151.24463 ]
 [115.569275]
 [177.19302 ]
 [169.84569 ]
 [144.61552 ]
 [145.42506 ]
 [18

In [12]:
print("Your score will be:  ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Others score will be: ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be:   [[190.60043]]
Others score will be:  [[188.25543]
 [171.84184]]
