In [1]:
import tensorflow as tf

In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [3]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

Instructions for updating:
Colocations handled automatically by placer.


In [4]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [8]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  1.7143625 
Prediction:
 [[151.13635]
 [184.6667 ]
 [180.24286]
 [198.06581]
 [140.15927]]
100 Cost:  1.6972862 
Prediction:
 [[151.12172]
 [184.67726]
 [180.23909]
 [198.05753]
 [140.17783]]
200 Cost:  1.680797 
Prediction:
 [[151.10757]
 [184.68753]
 [180.23547]
 [198.04938]
 [140.19597]]
300 Cost:  1.664888 
Prediction:
 [[151.09387]
 [184.6975 ]
 [180.23198]
 [198.04137]
 [140.2137 ]]
400 Cost:  1.6494738 
Prediction:
 [[151.08058]
 [184.70715]
 [180.2286 ]
 [198.0334 ]
 [140.23102]]
500 Cost:  1.6345637 
Prediction:
 [[151.06773]
 [184.71657]
 [180.22539]
 [198.02559]
 [140.24799]]
600 Cost:  1.6201525 
Prediction:
 [[151.05525]
 [184.72563]
 [180.22226]
 [198.01784]
 [140.26453]]
700 Cost:  1.6061863 
Prediction:
 [[151.04317]
 [184.73447]
 [180.21925]
 [198.01021]
 [140.28073]]
800 Cost:  1.5926512 
Prediction:
 [[151.03151]
 [184.74304]
 [180.21638]
 [198.0027 ]
 [140.29659]]
900 Cost:  1.5795256 
Prediction:
 [[151.02016]
 [184.75133]
 [180.21361]
 [197.99522]
 [140.31